version: '3'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myflix
    depends_on:
      - mongodb

  video-streaming:
    build: ./video-streaming
    ports:
      - "3001:3001"
    volumes:
      - ./video-streaming/videos:/app/videos
      #- ./video-streaming/nginx.conf:/etc/nginx/nginx.conf:ro

  watchlist-service:
    build: ./watchlist-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myflix
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
